

import React from 'react';
export const metadata = {
  title: "About Developers",
  description: "Generated by create next app",
};
const DevelopersPage = () => {
    return (
        <div>
            <h2>Info of developers</h2>
        </div>
    );
};

export default DevelopersPage;